{% set name = "zope.proxy" %}
{% set version = "6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zope_proxy-{{ version }}.tar.gz
  sha256: 9b70bf787fcbd3ecb86ba886d71e5cd857da0d6dbe2fcf2b6c24774f24747e2e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    # This has a C extension
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - zope.interface

test:
  imports:
    - zope.proxy

about:
  home: https://github.com/zopefoundation/zope.proxy
  license: ZPL-2.1
  license_family: OTHER
  license_file: LICENSE.txt
  summary: special objects which serve as mostly-transparent wrappers around another object
  description: |
    Proxies are special objects which serve as mostly-transparent wrappers
    around another object, intervening in the apparent behavior of the wrapped
    bject only when necessary to apply the policy (e.g., access checking,
    location brokering, etc.) for which the proxy is responsible.
    zope.proxy is implemented via a C extension module, which lets it do things
    like lie about its own __class__ that are difficult in pure Python (and
    were completely impossible before metaclasses). It also proxies all the
    internal slots (such as __int__/__str__/__add__).
  doc_url: https://zopeproxy.readthedocs.io/en/latest/
  dev_url: https://github.com/zopefoundation/zope.proxy

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - daf
